name: Pull Request CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Unit tests, sonar, and build
    runs-on: ubuntu-latest
    needs: [ create_release ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Current version
        run: ./gradlew currentVersion --no-daemon
      - name: Build and test
        run: ./gradlew build --no-daemon
      - name: Sonar
        run: ./gradlew sonar --no-daemon
      - name: Upload target for next job
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
